function getInfo() {
	window.numberOfQuestions = 	10;
	window.currentSlide = 		0;
	window.currentScore = 		0;
	window.title = 				"Chuck Trivia";
	window.questions = [		"WHO IS THE WOMAN CHUCK CAN'T STOP TALKING ABOUT IN THE FIRST EPISODE", 
								"WHAT ACTOR PLAYS CHUCKS OLD FRIEND FROM COLLEGE BRYCE LARKIN",
								"WHO IS CHUCKS BEST FRIEND", 
								"WHAT TYPE OF FOOD DOES BIG MIKE LOVE TO EAT", 
								"WHAT IS SARAHS REAL MIDDLE NAME",
								"WHAT IS THE SECRET CODENAME OF CHUCKS FATHER",
								"WHERE IN THE FIRST EPISODE DOES SARAH ASK CHUCK TO TRUST HER",
								"WHAT IS KNOWN IN MANY COUNTRIES AS THE MONTGOMERY",
								"WHAT SONG PLAYS AT THE END OF THE SERIES WHEN MORGAN IS TALKING TO CHUCK ABOUT SARAH",
							    "WHAT DOES SARAH NOT LIKE ON HER PIZZA" ];
	window.correctAnswer = [ 	"D", "C", "A", "B", "E", "A", "B", "D", "A", "C" ]; 
	window.answerA = [ 			"ELLIE", 
								"NATHAN FILLION", 
								"MORGAN", 
								"ARBYS", 
								"ELLA",
								"ORION",
								"HIS APPARTMENT",
								"BOTTLE OF LAFITE ROTHSCHILD, BOUQUET OF WHITE ROSES",
								"CRUEL AND BEAUTIFUL WORLD",
							    "MEAT" ];
	window.answerB = [ 			"VIVIAN", 
								"ZACHARY LEVI", 
								"SARAH", 
								"SUBWAY",
								"MARY",
								"CARMICHAEL",
								"THE BEACH",
								"1991 MARGAUX BORDEAUX,BLACK DINNER JACKET,WHITE ROSE",
								"RIVERS AND ROADS",
							    "PINNEAPPLE" ];
	window.answerC = [ 			"ANNA",
								"MATT BOMBER",
								"DEVON", 
								"BURGER KING", 
								"BELLE",
								"THE INTERSECT",
								"THE FAIR",
								"A BOX OF CHOCOLATES",
								"CREATURE FEAR",
							    "OLIVES" ];
	window.answerD = [ 			"JILL",  
								"SIMON BAKER",
								"LESTER", 
								"PIZZA HUT",
								"MAE",
								"AGENT X",
								"THEIR BENCH",
								"BOTTLE OF CHATEAU MARGAUX,WHITE DINNER JACKET,SINGLE RED ROSE",
								"SKINNY LOVE",
							    "OREGANO" ];
	window.answerE = [ 			"SARAH", 
								"JEFFEREY DONOVAN", 
								"MICHAEL", 
								"TACO BELL", 
								"LISA",
								"AGENT 99",
								"THE PARK",
								"A SINGLE RED ROSE",
								"ON MY WAY BACK HOME",
							    "RED CHILLI FLAKES" ];
	window.response = [ 		"JILL IS CHUCKS EX WHO DUMPED HIM FOR HIS FRIEND BRYCE LARKIN", 
								"MATT WOULD LATER GO ON TO STAR AS NEAL CAFFEREY IN WHITE COLLAR", 
								"FRIENDS SINCE THEY WERE VERY YOUNG MORGAN AND CHUCK ARE ALMOST INSEPERABLE", 
								"A VERY CLEAR SPONSER OF THE SHOW, SUBWAY APPEARS IN MULTIPLE DFFERENT WAYS ", 
								"DURING AN EMOTIONAL SCENE SARAH WHISPERS HER REAL MIDDLE NAME WHEN CHUCK CANNOT HEAR HER",
								"YOU FIND OUT LATER THAT ORION IS THE PERSON WHO MADE THE INTERSECT AND ALSO CHUCKS FATHER",
								"REFERENCED IN THE FINAL EPISODE WITH CHUCK ASKING SARAH TO TRUST HIM, ITS A VERY SIGNIFICANT SPOT",
								"A LOVE PROFESSOR FOR SPIES ROAN MONTGOMERY TEACHES CHUCK THE ART OF SEDUCTION",
								"AS THE TWO BOYS SIT ON THE FOUNTAIN MORGAN TELLS CHUCK HIS THEORY ABOUT CHUCK AND SARAH",
							    "OF THE FEW THINGS CHUCK ACTUALLY KNOWS ABOUT SARAH HER DISLIKE OF OLIVES IS ONE OF THEM" ];
							
}
						